config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :mountain_routes, path: 'przejscia' do
    get :areas, on: :collection
    get :custom_difficulties, on: :collection
  end
  resources :app_settings, path: "konfiguracja"

  resources :users, only: [:show, :destroy]

  namespace :admin do
    resources :users
  end

  namespace :messaging do
    resources :comments, only: [:create, :update, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  resource :registration, only: [:new, :create]
  resource :password_reset, only: [:new, :create, :edit, :update]
  resource :password, only: [:edit, :update]

  get "up" => "rails/health#show", as: :rails_health_check
  get "/pages/:page" => "pages#show"

  get 'trudnosci' => 'pages#dificulties_table'
  get 'polityka-prywatnosci' => 'pages#polityka_prywatnosci'
  get 'regulamin' => 'pages#regulamin'
  get 'admin' => 'pages#admin'
  get 'przejscia' => 'mountain_routes#index'

  root "mountain_routes#index"
end

app/models/mountain_route.rb
# == Schema Information
#
# Table name: mountain_routes
#
#  id                    :uuid             not null, primary key
#  activity_date         :date             not null
#  area                  :string
#  custom_difficulty     :string
#  equipped              :boolean
#  french_difficulty     :integer
#  hidden                :boolean          default(FALSE), not null
#  length                :integer
#  multipitch            :boolean
#  multipitch_difficulty :string
#  multipitch_lead       :integer
#  multipitch_number     :integer
#  multipitch_style      :integer
#  name                  :string           not null
#  partner               :string
#  slug                  :string           not null
#  sport_type            :integer          not null
#  style                 :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :uuid             not null
#
# Indexes
#
#  index_mountain_routes_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class MountainRoute < ApplicationRecord
  include PgSearch::Model
  extend FriendlyId

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_fill: [150, 150]
  end

  normalizes :area, with: -> area { area&.downcase&.strip&.split(' ')&.collect(&:capitalize).join(' ') }
  normalizes :custom_difficulty, with: -> custom_difficulty { custom_difficulty =~ /\d/ ? custom_difficulty&.strip : custom_difficulty&.strip&.upcase }
  normalizes :partner, with: -> partner { partner&.downcase&.strip&.split(/[\s]/)&.collect(&:strip)&.join(' ')&.split(/[,'+]/)&.collect(&:strip)&.map(&:capitalize).join(' + ') }

  has_rich_text :description

  pg_search_scope :search,
    against: [:name, :area, :partner],
    associated_against: {
      user: [:first_name, :last_name],
      partners: [:first_name, :last_name],
      rich_text_description: [:body]
    },
    using: [:tsearch]

  friendly_id :name_and_date, use: :slugged

  enum sport_type: {
    sport_climbing: 0, trad_climbing: 1, winter_climbing: 2, speleo: 3, skimo: 4
  }

  enum multipitch_style: {
    'OS': 0, 'RP': 1, 'FL': 2, 'AF': 3
  }, _prefix: :multipitch

  enum style: {
    'OS': 0, 'RP': 1, 'FL': 2, 'AF': 3
  }
  enum french_difficulty: {
    '1': 0, '2': 1, '2+': 2, '3': 3, '4a': 4, '4b': 5, '4c': 6, '5a': 7,
    '5b': 8, '5c': 9, '6a': 10, '6a+': 11, '6b': 12, '6b+': 13, '6c': 14,
    '6c+': 15, '7a': 16, '7a+': 17, '7b': 18, '7b+': 19, '7c': 20, '7c+': 21,
    '8a': 22, '8a+': 23, '8b': 24, '8b+': 25, '8c': 26, '8c+': 27, '9a': 28,
    '9a+': 29, '9b': 30, '9b+': 31
  }

  belongs_to :user
  has_many :mountain_route_partners, dependent: :destroy
  has_many :partners, through: :mountain_route_partners, source: :user
  has_many :comments, as: :commentable, class_name: 'Messaging::Comment'

  validates :user_id, :activity_date, :sport_type, :name, :area,
    :partners, presence: true

  with_options if: :climbing? do |climbing|
    climbing.validates :french_difficulty, presence: true
    climbing.validates :french_difficulty, inclusion: { in: french_difficulties.keys }
    climbing.validates :style,             presence: true
    climbing.validates :style,             inclusion: { in: styles.keys }
    climbing.validates :equipped,          inclusion: { in: [true, false], message: I18n.t('errors.messages.blank') }

    with_options if: [:multipitch?, :climbing?] do |multipitch|
      multipitch.validates :multipitch_style, :multipitch_number,
        :multipitch_lead, :multipitch_difficulty, :length, presence: true
      multipitch.validates :multipitch,       inclusion: { in: [true, false], message: I18n.t('errors.messages.blank') }
      multipitch.validates :multipitch_style, inclusion: { in: self.multipitch_styles.keys }
    end
  end

  def climbing?
    ["sport_climbing", "trad_climbing", "winter_climbing"].include?(sport_type)
  end

  def name_and_date
    return nil unless activity_date.present? && name.present?

    "#{activity_date&.to_date} #{name}"
  end

  def team
    [partners.map(&:name), partner].flatten.reject(&:empty?).compact.join(' + ').strip
  end
end

app/controllers/mountain_routes_controller.rb
class MountainRoutesController < ApplicationController
  before_action :set_mountain_route, only: %i[ show edit update destroy ]

  def custom_difficulties
    all_custom_difficulties = MountainRoute.all.distinct.pluck(:custom_difficulty)
    @custom_difficulties = all_custom_difficulties.select do |custom_difficulty|
      custom_difficulty.downcase.include?(params[:q].downcase)
    end

    render layout: false
  end

  def areas
    all_areas = MountainRoute.all.distinct.pluck(:area)
    @areas = all_areas.select do |area|
      area.downcase.include?(params[:q].downcase)
    end

    render layout: false
  end

  def index
    mountain_routes = MountainRoute.arel_table
    query = mountain_routes[:id].not_eq(nil)
    query = query.and(mountain_routes[:activity_date].gteq( Date.new(params.dig(:year).to_i, 1, 1).beginning_of_year)) if params.dig(:year).present?
    query = query.and(mountain_routes[:sport_type].eq(params.dig(:sport_type))) if params.dig(:sport_type).present?

    @mountain_routes = MountainRoute.where(query).search(params.dig(:search)).order(activity_date: :desc) if params.dig(:search).present?
    @mountain_routes = MountainRoute.where(query).order(activity_date: :desc) if params.dig(:search).blank?

    @mountain_routes = MountainRoutePolicy::Scope.new(current_user, @mountain_routes).resolve

    @pagy, @mountain_routes = pagy(@mountain_routes)
  end

  def show
    authorize @mountain_route
  end

  def new
    @mountain_route = MountainRoute.new

    authorize @mountain_route

    if params[:mountain_route].present?
      @mountain_route.assign_attributes(mountain_route_params)
    else
      @mountain_route.assign_attributes(sport_type: current_user.last_sport_type) if current_user.last_sport_type.present?
    end

    @mountain_route.partner_ids = [current_user.id]
  end

  def edit
    authorize @mountain_route

    @mountain_route.assign_attributes(mountain_route_params) if params[:mountain_route].present?
  end

  def create
    @mountain_route = current_user.mountain_routes.new(mountain_route_params)
    @mountain_route.user = current_user

    authorize @mountain_route

    respond_to do |format|
      if @mountain_route.save
        current_user.update(last_sport_type: @mountain_route.sport_type)
        if ActiveModel::Type::Boolean.new.cast(params[:next])
          format.html { redirect_to new_mountain_route_url(next: true), notice: t('mountain_routes.create.success') }
        else
          format.html { redirect_to mountain_route_url(@mountain_route), notice: t('mountain_routes.create.success') }
        end
        format.json { render :show, status: :created, location: @mountain_route }
      else
        format.html { render :new, status: :unprocessable_entity, locals: { mountain_route: @mountain_route, params: mountain_route_params } }
        format.json { render json: @mountain_route.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @mountain_route

    respond_to do |format|
      if @mountain_route.update(mountain_route_params)
        current_user.update(last_sport_type: @mountain_route.sport_type)
        format.html { redirect_to mountain_route_url(@mountain_route), notice: t("mountain_routes.update.success") }
        format.json { render :show, status: :ok, location: @mountain_route }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mountain_route.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @mountain_route

    @mountain_route.destroy!

    respond_to do |format|
      format.html { redirect_to mountain_routes_url, notice: "Mountain route was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_mountain_route
      @mountain_route = MountainRoute.friendly.find(params[:id])
    end

    def mountain_route_params
      params.require(:mountain_route).permit(
        :activity_date, :sport_type, :area, :custom_difficulty, :equipped,
        :french_difficulty, :length, :multipitch, :multipitch_difficulty,
        :multipitch_lead, :multipitch_number, :multipitch_style, :name,
        :partner, :style, :description, :hidden,
        images: [], partner_ids: []
      )
    end
end

app/helpers/mountain_routes_helper.rb
module MountainRoutesHelper
  def team_link(route)
    [
      route.partners.map { |partner| link_to(partner.name, user_path(partner), class: "rounded-lg text-blue-500 inline-block font-medium") }
    ].flatten.reject(&:empty?).compact.join(' + ').strip
  end
end

app/views/mountain_routes/_form.html.erb
<% if mountain_route.sport_type.present? %>
  <%= render partial: "mountain_routes/forms/#{mountain_route.sport_type}", locals: { mountain_route: mountain_route } %>
<% end %>

app/views/mountain_routes/_mountain_route.html.erb
<div id="<%= dom_id mountain_route %>">
  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.name') %>:</strong>
    <%= mountain_route.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.sport_type') %>:</strong>
    <%= MountainRoute.human_enum_name(:sport_type, mountain_route.sport_type) %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.activity_date') %>:</strong>
    <%= mountain_route.activity_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.area') %>:</strong>
    <%= mountain_route.area %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.equipped') %>:</strong>
    <%= I18n.t mountain_route.equipped %>
  </p>

  <% if mountain_route.custom_difficulty? %>
    <p class="my-5">
      <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.custom_difficulty') %>:</strong>
      <%= mountain_route.custom_difficulty %>
    </p>
  <% end %>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.french_difficulty') %>:</strong>
    <%= mountain_route.french_difficulty %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.style') %>:</strong>
    <%= mountain_route.style %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.length') %>:</strong>
    <%= mountain_route.length %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.multipitch') %>:</strong>
    <%= I18n.t mountain_route.multipitch %>
  </p>

  <% if mountain_route.multipitch? %>
    <p class="my-5">
      <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.multipitch_difficulty') %>:</strong>
      <%= mountain_route.multipitch_difficulty %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.multipitch_lead') %>:</strong>
      <%= mountain_route.multipitch_lead %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.multipitch_number') %>:</strong>
      <%= mountain_route.multipitch_number %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.multipitch_style') %>:</strong>
      <%= mountain_route.multipitch_style %>
    </p>
  <% end %>

  <p class="my-5">
    <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.team') %>:</strong>
    <%= sanitize team_link(mountain_route) %>
  </p>

  <% if mountain_route.description.present? %>
    <p class="my-5">
      <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.description') %>:</strong>
      <%= mountain_route.description %>
    </p>
  <% end %>

  <% if mountain_route.images.attached? %>
    <p class="my-5">
      <strong class="block font-medium mb-1"><%= t('activerecord.attributes.mountain_route.images') %>:</strong>
      <% mountain_route.images.each do |image| %>
        <div data-controller="modal">
          <dialog data-modal-target="dialog" class="p-8 rounded-lg backdrop:bg-black/80">
            <%= image_tag image, class: "rounded-lg" %>
            <button autofocus data-action="modal#close" class="px-2.5 py-1 bg-blue-500 text-white text-sm rounded">Close</button>
          </dialog>

          <%= image_tag image.variant(:thumb), class: "rounded-lg", data: { action: "click->modal#open" } %>
        </div>
      <% end %>
    </p>
  <% end %>


  <% if action_name != "show" %>
    <%= link_to t('.show', default: t("helpers.links.show")), mountain_route, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% if policy(mountain_route).edit? %>
      <%= link_to t('.edit', default: t("helpers.links.edit")), edit_mountain_route_path(mountain_route), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  <% end %>
</div>

app/views/mountain_routes/_responsive_table.html.erb
<table class="min-w-full divide-y divide-gray-300">
  <thead class="bg-gray-50">
    <tr>
      <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6" width=10%><%= t('.date') %></th>
      <th scope="col" class="hidden py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 lg:table-cell" width=30%><%= t('.name') %></th>
      <th scope="col" class="hidden py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 lg:table-cell" width=10><%= t('.difficulty') %></th>
      <th scope="col" class="hidden py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 lg:table-cell" width=40%><%= t('.team') %></th>
      <th scope="col" class="hidden relative py-3.5 pl-3 pr-4 sm:pr-6 lg:table-cell" width=10%></th>
    </tr>
  </thead>
  <tbody class="divide-y divide-gray-200 bg-white">
    <% mountain_routes.each do |mountain_route| %>
      <tr class="even:bg-gray-50">
        <td class="lg:hidden">
          <dl class="font-normal lg:hidden">
            <dd class="mt-1 truncate text-gray-700"><%= link_to mountain_route.name, mountain_route %></dd>
            <% if mountain_route.custom_difficulty.present? %>
              <dd class="mt-1 truncate text-gray-700"><%= link_to mountain_route.custom_difficulty, mountain_route %></dd>
            <% end %>
            <dd class="mt-1 truncate text-gray-700"><%= link_to mountain_route.activity_date, mountain_route %></dd>
            <dd class="mt-1 truncate text-gray-500 sm:hidden"><%= link_to MountainRoute.human_enum_name(:sport_type, mountain_route.sport_type), mountain_route %></dd>
            <dd class="mt-1 truncate text-gray-500 sm:hidden"><%= link_to mountain_route.area, mountain_route %></dd>
            <dd class="font-medium text-gray-900"><%= link_to mountain_route.partners.collect { |partner| partner.name }.join(', '), mountain_route %></dd>
          </dl>
        </td>
        <td class="hidden whitespace-nowrap py-5 pl-4 pr-3 text-sm sm:pl-0 lg:table-cell">
          <div class="flex items-center">
            <div class="h-11 w-11 ml-3 flex-shrink-0">
              <% if mountain_route.images.attached? %>
                <% image = mountain_route.images.first %>
                <%= image_tag image.variant(:thumb), class: "h-11 w-11 rounded-full" %>
              <% else %>
                <span class="inline-flex h-10 w-10 items-center justify-center rounded-full bg-gray-500">
                  <span class="font-medium leading-none text-white"><%= MountainRoute.human_enum_name(:sport_type, mountain_route.sport_type).split.map(&:first).join %></span>
                </span>
              <% end %>
            </div>
            <div class="ml-4">
              <div class="font-medium text-gray-900"><%= link_to mountain_route.activity_date, mountain_route %></div>
              <div class="mt-1 text-gray-500"><%= link_to MountainRoute.human_enum_name(:sport_type, mountain_route.sport_type), mountain_route %></div>
            </div>
          </div>
        </td>
        <td class="hidden whitespace-nowrap px-3 py-5 text-sm text-gray-500 lg:table-cell">
          <div class="text-gray-900"><%= link_to mountain_route.name, mountain_route %></div>
          <div class="mt-1 text-gray-500"><%= link_to mountain_route.area, mountain_route %></div>
        </td>
        <td class="hidden whitespace-nowrap px-3 py-5 text-sm text-gray-500 lg:table-cell">
          <div class="font-medium text-gray-900 text-center"><%= mountain_route.french_difficulty %></div>
          <div class="mt-1 text-gray-500 text-center"><%= mountain_route.custom_difficulty %></div>
        </td>
        <td class="hidden whitespace-nowrap px-3 py-5 text-sm text-gray-500 lg:table-cell">
          <div class="font-medium text-gray-900"><%= sanitize team_link(mountain_route) %></div>
          <div class="mt-1 text-gray-500"><%= mountain_route.partner %></div>
        </td>
        <td class="hidden relative whitespace-nowrap py-5 pl-3 pr-4 text-right text-sm font-medium sm:pr-0 lg:table-cell">
          <% if policy(mountain_route).edit? %>
            <%= link_to edit_mountain_route_path(mountain_route), class: "text-yellow-600 hover:text-yellow-900" do %>
              <span class="mr-3"><%= t('edit') %></span>
            <% end %>
            <%= button_to mountain_route, method: :delete, form: { data: { turbo_confirm: t('confirm') } }, class: "text-red-600 hover:text-red-900" do %>
              <span class="mr-3"><%= t('delete') %></span>
            <% end %>
            <% if mountain_route.hidden? %>
              <span class="mr-3 text-gray-500"><%= t('.hidden') %></span>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/mountain_routes/_table.html.erb
<div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table
          class="min-w-full text-left text-sm text-surface dark:text-surface">
          <thead
            class="border-b border-neutral-200 bg-white font-medium dark:border-white/10 dark:bg-body-dark">
            <tr>
              <th scope="col" class="px-6 py-4"><abbr title="Typ">Typ</abbr></th>
              <th scope="col" class="px-6 py-4"><abbr title="Data">Data</abbr></th>
              <th scope="col" class="px-6 py-4"><abbr title="Nazwa">Nazwa</abbr></th>
              <th scope="col" class="px-6 py-4"><abbr title="Rejon">Rejon</abbr></th>
              <th scope="col" class="px-6 py-4"><abbr title="Trudność">Trudność</abbr></th>
              <th scope="col" class="px-6 py-4"><abbr title="Zespół">Zespół</abbr></th>
            </tr>
          </thead>
          <tbody>
            <% mountain_routes.each do |mountain_route| %>

              <tr class="border-b border-neutral-200 bg-black/[0.02] dark:border-white/10">
                <th class="whitespace-nowrap px-6 py-4 font-medium"><%= link_to MountainRoute.human_enum_name(:sport_type, mountain_route.sport_type), mountain_route %></td>
                <th class="whitespace-nowrap px-6 py-4 font-medium"><%= link_to mountain_route.activity_date, mountain_route %></td>
                <td class="whitespace-nowrap px-6 py-4"><%= link_to mountain_route.name, mountain_route %></td>
                <td class="whitespace-nowrap px-6 py-4"><%= link_to mountain_route.area, mountain_route %></td>
                <td class="whitespace-nowrap px-6 py-4"><%= mountain_route.french_difficulty %></td>
                <td class="whitespace-nowrap px-6 py-4"><%= sanitize team_link(mountain_route) %></td>
                <td>
                  <div>
                    <% if policy(mountain_route).edit? %>
                      <%= link_to edit_mountain_route_path(mountain_route), class: '' do %>
                        <span class="icon is-small">Edytuj<i class=""></i></span>
                      <% end %>
                      <%= button_to mountain_route, method: :delete, data: { confirm: I18n.t('.are_you_sure') }, class: '' do %>
                        <span class="icon is-small">Usuń<i class=""></i></span>
                      <% end %>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/mountain_routes/areas.html.erb
<% @areas.each do |area| %>
  <li class="text-gray-700 block px-4 py-2 text-sm" role='option'><%= area %></li>
<% end %>

app/views/mountain_routes/custom_difficulties.html.erb
<% @custom_difficulties.each do |difficulty| %>
  <li class="text-gray-700 block px-4 py-2 text-sm" role='option'><%= difficulty %></li>
<% end %>

app/views/mountain_routes/edit.html.erb
<div class="mx-auto w-full">
  <h1 class="font-bold text-4xl"><%= t(".title") %></h1>

  <%= render "form", mountain_route: @mountain_route %>

  <%= link_to t('show'), @mountain_route, class: "ml-2 rounded-lg p-6 bg-blue-100 inline-block font-medium" %>
  <%= link_to t('back'), mountain_routes_path, class: "ml-2 rounded-lg p-6 bg-gray-100 inline-block font-medium" %>
</div>

app/views/mountain_routes/index.html.erb
<div class="w-full">
  <%= render 'shared/flash' %>

  <div class="grid lg:grid-cols-2 gap-4">
    <div class="">
      <%= form_with url: mountain_routes_path, method: :get do %>
        <div class="grid lg:grid-cols-3 gap-4">
              <%= text_field_tag :search, params[:search], class: "", placeholder: t('.search') %>
              <%= text_field_tag :year, params[:year], class: "", placeholder: t('.year') %>
              <%= select_tag :sport_type, options_for_select(MountainRoute.sport_types.keys.map { |sport_type| [t("activerecord.attributes.mountain_route.sport_types.#{sport_type}"), sport_type] }, params[:sport_type]), onchange: "this.form.submit();", include_blank: t('.sport_type'), class: "text-gray-500" %>
              <%= submit_tag t('.search'), class: "hidden" %>
        </div>
      <% end %>
    </div>
    <div class="flex flex-row-reverse">
      <%= link_to t('.new'), new_mountain_route_path, class: "max-sm:w-full rounded-lg py-3 px-5 bg-yellow-300 justify-end font-medium" %>
    </div>
  </div>

  <div id="mountain_routes" class="mt-5 min-w-full">
    <%= render 'responsive_table', mountain_routes: @mountain_routes %>

    <div class="flex py-5 justify-center">
      <%== pagy_nav(@pagy) %>
    </div>
  </div>
</div>

app/views/mountain_routes/new.html.erb
<h1 class="font-bold text-4xl">
  <% if ActiveModel::Type::Boolean.new.cast(params[:next]) %>
    <%= t(".next_title") %>
  <% else %>
    <%= t(".title") %>
  <% end %>
</h1>
<%= render 'shared/flash' %>

<div class="grid sm:grid-cols-2 md:grid-cols-5 gap-5 mt-5">
  <% MountainRoute.sport_types.keys.each do |sport_type| %>
    <div class="col-span-1 text-center">
      <% if sport_type == @mountain_route.sport_type %>
        <%= link_to t("activerecord.attributes.mountain_route.sport_types.#{sport_type}"), new_mountain_route_path(mountain_route: { sport_type: sport_type }), class: "rounded-lg py-3 px-5 bg-yellow-300 inline-block font-medium" %>
      <% else %>
        <%= link_to t("activerecord.attributes.mountain_route.sport_types.#{sport_type}"), new_mountain_route_path(mountain_route: { sport_type: sport_type }), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <% end %>
    </div>
  <% end %>
</div>

<%= render "form", mountain_route: @mountain_route %>

app/views/mountain_routes/show.html.erb
<%= render 'shared/flash' %>
<%= render 'mountain_route_responsive', mountain_route: @mountain_route %>

<div class="flex md:my-5 gap-5 w-full items-center text-center mb-5">
  <% if policy(@mountain_route).edit? %>
    <%= link_to edit_mountain_route_path(@mountain_route), class: "w-1/3 rounded-lg p-6 bg-green-100 font-medium" do %>
      <%= t('edit') %>
    <% end %>
    <div class="w-1/3 rounded-lg p-6 bg-red-100 ">
      <%= button_to mountain_route_path(@mountain_route), method: :delete, form: { data: { turbo_confirm: t('confirm') } }, class: "text-red-600 hover:text-red-900" do %>
        <div class="font-medium"><%= t('.destroy') %></div>
      <% end %>
    </div>
  <% end %>
  <%= link_to mountain_routes_path, class: "w-1/3 rounded-lg bg-gray-100 p-6 font-medium" do %>
    <%= t('back') %>
  <% end %>
</div>