config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :mountain_routes, path: 'przejscia' do
    get :areas, on: :collection
    get :custom_difficulties, on: :collection
  end
  resources :app_settings, path: "konfiguracja"

  resources :users, only: [:show, :destroy]

  namespace :admin do
    resources :users
  end

  namespace :messaging do
    resources :comments, only: [:create, :update, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  resource :registration, only: [:new, :create]
  resource :password_reset, only: [:new, :create, :edit, :update]
  resource :password, only: [:edit, :update]

  get "up" => "rails/health#show", as: :rails_health_check
  get "/pages/:page" => "pages#show"

  get 'trudnosci' => 'pages#dificulties_table'
  get 'polityka-prywatnosci' => 'pages#polityka_prywatnosci'
  get 'regulamin' => 'pages#regulamin'
  get 'admin' => 'pages#admin'
  get 'przejscia' => 'mountain_routes#index'

  root "mountain_routes#index"
end

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice.html_safe %></p>
<% end %>

<% if alert.present? %>
  <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert.html_safe %></p>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-800" data-controller='toggle'>
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <button data-action='click->toggle#toggle touch->toggle#toggle' type="button" class="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Menu</span>
          <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <a href="/" class="flex-shrink-0">
          <img class="h-8 w-auto invert" src="https://pza.org.pl/wp-content/uploads/2023/11/pza_2023-1.png" alt="Your Company">
          </a>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <a href="/przejscia" class="bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium" aria-current="page">Przejścia PZA</a>
            <% if user_signed_in? && current_user.admin? %>
              <a href="/admin" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Administracja</a>
            <% end %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <div data-controller="dropdown" class="relative ml-3">
          <div>
            <button type="button"  data-action="click->dropdown#toggle click@window->dropdown#hide" class="relative flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="absolute -inset-1.5"></span>
              <% if user_signed_in? %>
                <%= render partial: "users/avatar", locals: { user: current_user, size: "h-8 w-8 rounded-full" } %>
              <% else %>
                <img class="h-8 w-8 rounded-full" src="https://t4.ftcdn.net/jpg/05/49/98/39/360_F_549983970_bRCkYfk0P6PP5fKbMhZMIb07mCJ6esXL.jpg" alt="">
              <% end %>
            </button>
          </div>

          <div data-target="dropdown.menu" class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
            <% if user_signed_in? %>
              <%= link_to t("your_profile"), user_path(Current.user), class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-0" %>
              <%= link_to t("settings"), edit_password_path, class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-1" %>
              <%= link_to "Regulamin", '/regulamin', class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-2" %>
              <%= link_to "Polityka Prywatności", '/polityka-prywatnosci', class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-2" %>
              <%= button_to t("logout"), session_path, method: :delete, class: "block px-4 py-2 text-sm text-red-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-2" %>
            <% else %>
              <%= link_to t("login"), new_session_path, class: "block px-4 py-2 text-sm text-green-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-1" %>
              <%= link_to t("register"), new_registration_path, class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-2" %>
              <%= link_to "Regulamin", '/regulamin', class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-2" %>
              <%= link_to "Polityka Prywatności", '/polityka-prywatnosci', class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: "-1", id: "user-menu-item-2" %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div data-toggle-target='toggleable' class="hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pb-3 pt-2">
      <a href="/" class="bg-gray-900 text-white block rounded-md px-3 py-2 text-base font-medium" aria-current="page">Przejścia PZA</a>
      <% if user_signed_in? && current_user.admin? %>
        <a href="/admin" class="text-gray-300 hover:bg-gray-700 hover:text-white block rounded-md px-3 py-2 text-base font-medium">Administracja</a>
      <% end %>
    </div>
  </div>
</nav>