config/routes.rb
Rails.application.routes.draw do
  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :mountain_routes, path: 'przejscia' do
    get :areas, on: :collection
    get :custom_difficulties, on: :collection
  end
  resources :app_settings, path: "konfiguracja"

  resources :users, only: [:show, :destroy]

  namespace :admin do
    resources :users
  end

  namespace :messaging do
    resources :comments, only: [:create, :update, :destroy]
  end

  resource :session, only: [:new, :create, :destroy]
  resource :registration, only: [:new, :create]
  resource :password_reset, only: [:new, :create, :edit, :update]
  resource :password, only: [:edit, :update]

  get "up" => "rails/health#show", as: :rails_health_check
  get "/pages/:page" => "pages#show"

  get 'trudnosci' => 'pages#dificulties_table'
  get 'polityka-prywatnosci' => 'pages#polityka_prywatnosci'
  get 'regulamin' => 'pages#regulamin'
  get 'admin' => 'pages#admin'
  get 'przejscia' => 'mountain_routes#index'

  root "mountain_routes#index"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :uuid             not null, primary key
#  admin           :boolean          default(FALSE)
#  email           :string
#  first_name      :string
#  last_name       :string
#  last_sport_type :string
#  password_digest :string
#  slug            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_slug  (slug) UNIQUE
#
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  has_secure_password

  generates_token_for :password_reset, expires_in: 15.minutes do
    password_salt&.last(10)
  end

  normalizes :email, with: -> (email) { email.strip.downcase }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :added_mountain_routes, dependent: :destroy, class_name: 'MountainRoute', foreign_key: :user_id
  has_many :mountain_route_partners, dependent: :destroy
  has_many :mountain_routes, through: :mountain_route_partners, source: :mountain_route
  has_many :comments, dependent: :destroy, class_name: 'Messaging::Comment', foreign_key: :user_id

  def name
    "#{first_name} #{last_name}"
  end

  def title
    "-"
  end

  def club
    "-"
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :set_user, only: %i[ show edit update destroy ]
    before_action :authenticate_user!
    before_action :authenticate_admin!

    # GET /users or /users.json
    def index
      @users = User.all
    end

    # GET /users/1 or /users/1.json
    def show
    end

    # GET /users/new
    def new
      @user = User.new
    end

    # GET /users/1/edit
    def edit
    end

    # POST /users or /users.json
    def create
      @user = User.new(user_params.merge(password: SecureRandom.hex(10)))

      respond_to do |format|
        if @user.save
          format.html { redirect_to admin_user_url(@user), notice: "User was successfully created." }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /users/1 or /users/1.json
    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to admin_user_url(@user), notice: "User was successfully updated." }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /users/1 or /users/1.json
    def destroy
      @user.destroy!

      respond_to do |format|
        format.html { redirect_to admin_users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.friendly.find(params[:id])
      end

      def authenticate_admin!
        redirect_to root_path, alert: "Nie masz dostępu!" unless current_user.admin?
      end

      # Only allow a list of trusted parameters through.
      def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :avatar, :admin)
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
    authorize @user
  end

  def destroy
    @user = User.friendly.find(params[:id])
    authorize @user

    @user.destroy

    redirect_to root_path, notice: t('.destroyed')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_with(model: [:admin, user], class: "contents") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="my-5">
    <%= form.label :admin %>
    <%= form.check_box :admin, class: "" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Imię i nazwisko:</strong>
    <%= user.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Email:</strong>
    <%= user.email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Zobacz", admin_user_path(user), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edytuj", edit_admin_user_path(user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%= button_to "Usuń", admin_user_path(user), method: :delete, data: { confirm: "Jesteś pewnien?" }, class: "rounded-lg py-3 ml-2 px-5 bg-red-500 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", user: @user %>

  <div class='flex items-center justify-between mt-5'>
  <%= link_to "Zobacz", [:admin, @user], class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= button_to "Usuń", admin_user_path(@user), method: :delete, data: { confirm: "Jesteś pewnien?" }, class: "rounded-lg py-3 ml-2 px-5 bg-red-500 inline-block font-medium" %>
  <%= link_to "Powrót", admin_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
</div>

app/views/admin/users/index.html.erb
<div class="w-full">
  <div class="px-4 sm:px-6 lg:px-8">
    <div class="sm:flex sm:items-center">
      <div class="sm:flex-auto">
        <h1 class="text-base font-semibold leading-6 text-gray-900">Użytkownicy</h1>
        <p class="mt-2 text-sm text-gray-700">Zarządzenie użytkownikami.</p>
      </div>
      <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
        <%= link_to "Nowy użytkownik", new_admin_user_path, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      </div>
    </div>
    <div class="mt-8 flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <table class="min-w-full divide-y divide-gray-300">
            <thead>
              <tr>
                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Kto</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Organizacja</th>
                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Dostęp</th>
                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
                  <span class="sr-only">Edytuj</span>
                </th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200 bg-white">
              <% @users.each do |user| %>
                <tr>
                  <td class="whitespace nowrap py-5 pl-4 pr-3 text-sm sm:pl-0">
                    <div class="flex items-center">
                      <div class="h-11 w-11 flex-shrink-0">
                        <%= render partial: "users/avatar", locals: { user: user, size: "h-11 w-11" } %>
                      </div>
                      <div class="ml-4">
                        <div class="font-medium text-gray-900"><%= link_to user.name, user %></div>
                        <div class="mt-1 text-gray-500"><%= link_to user.email, user %></div>
                      </div>
                    </div>
                  </td>
                  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                    <div class="text-gray-900"><%= user.title %></div>
                    <div class="mt-1 text-gray-500"><%= user.club %></div>
                  </td>
                  <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500"><%= user.admin? ? "Admin" : "Zwykły" %></td>
                  <td class="relative whitespace-nowrap py-5 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                    <%= link_to edit_admin_user_path(user), class: "text-indigo-600 hover:text-indigo-900" do %>
                      Edytuj<span class="sr-only">, <%= user.name %></span>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user</h1>

  <%= render "form", user: @user %>

  <%= link_to "Back to users", admin_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user %>

    <%= link_to "Edit this user", edit_admin_user_path(@user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this user", admin_user_path(@user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to users", admin_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>